const statesData = [
  { code: 'AP', name: 'Andhra Pradesh', capital: 'Amaravati', coords: [80.6278, 16.5062], districts: ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool'] },
  { code: 'AR', name: 'Arunachal Pradesh', capital: 'Itanagar', coords: [93.6053, 27.1004], districts: ['Tawang', 'West Kameng', 'East Kameng', 'Papum Pare', 'Kurung Kumey'] },
  { code: 'AS', name: 'Assam', capital: 'Dispur', coords: [91.7983, 26.1433], districts: ['Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon'] },
  { code: 'BR', name: 'Bihar', capital: 'Patna', coords: [85.1376, 25.5941], districts: ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Purnia'] },
  { code: 'CT', name: 'Chhattisgarh', capital: 'Raipur', coords: [81.6296, 21.2514], districts: ['Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Rajnandgaon'] },
  { code: 'GA', name: 'Goa', capital: 'Panaji', coords: [73.8278, 15.4909], districts: ['North Goa', 'South Goa'] },
  { code: 'GJ', name: 'Gujarat', capital: 'Gandhinagar', coords: [72.6369, 23.2156], districts: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar'] },
  { code: 'HR', name: 'Haryana', capital: 'Chandigarh', coords: [76.7794, 30.7333], districts: ['Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Rohtak'] },
  { code: 'HP', name: 'Himachal Pradesh', capital: 'Shimla', coords: [77.1734, 31.1048], districts: ['Shimla', 'Mandi', 'Kangra', 'Solan', 'Kullu'] },
  { code: 'JH', name: 'Jharkhand', capital: 'Ranchi', coords: [85.3096, 23.3441], districts: ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar'] },
  { code: 'KA', name: 'Karnataka', capital: 'Bengaluru', coords: [77.5946, 12.9716], districts: ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubballi', 'Belagavi'] },
  { code: 'KL', name: 'Kerala', capital: 'Thiruvananthapuram', coords: [76.9366, 8.5241], districts: ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur', 'Kollam'] },
  { code: 'MP', name: 'Madhya Pradesh', capital: 'Bhopal', coords: [77.4126, 23.2599], districts: ['Indore', 'Bhopal', 'Jabalpur', 'Gwalior', 'Ujjain'] },
  { code: 'MH', name: 'Maharashtra', capital: 'Mumbai', coords: [72.8777, 19.0760], districts: ['Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik'] },
  { code: 'MN', name: 'Manipur', capital: 'Imphal', coords: [93.9368, 24.8170], districts: ['Imphal West', 'Imphal East', 'Thoubal', 'Bishnupur', 'Churachandpur'] },
  { code: 'ML', name: 'Meghalaya', capital: 'Shillong', coords: [91.8933, 25.5788], districts: ['East Khasi Hills', 'West Garo Hills', 'Jaintia Hills', 'Ri Bhoi', 'South Garo Hills'] },
  { code: 'MZ', name: 'Mizoram', capital: 'Aizawl', coords: [92.7176, 23.7271], districts: ['Aizawl', 'Lunglei', 'Saiha', 'Champhai', 'Kolasib'] },
  { code: 'NL', name: 'Nagaland', capital: 'Kohima', coords: [94.1086, 25.6751], districts: ['Dimapur', 'Kohima', 'Mokokchung', 'Tuensang', 'Wokha'] },
  { code: 'OR', name: 'Odisha', capital: 'Bhubaneswar', coords: [85.8245, 20.2961], districts: ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Brahmapur', 'Sambalpur'] },
  { code: 'PB', name: 'Punjab', capital: 'Chandigarh', coords: [76.7794, 30.7333], districts: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda'] },
  { code: 'RJ', name: 'Rajasthan', capital: 'Jaipur', coords: [75.7873, 26.9124], districts: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Ajmer'] },
  { code: 'SK', name: 'Sikkim', capital: 'Gangtok', coords: [88.6138, 27.3389], districts: ['East Sikkim', 'West Sikkim', 'North Sikkim', 'South Sikkim'] },
  { code: 'TN', name: 'Tamil Nadu', capital: 'Chennai', coords: [80.2707, 13.0827], districts: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem'] },
  { code: 'TG', name: 'Telangana', capital: 'Hyderabad', coords: [78.4867, 17.3850], districts: ['Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam'] },
  { code: 'TR', name: 'Tripura', capital: 'Agartala', coords: [91.2868, 23.8315], districts: ['West Tripura', 'Gomati', 'South Tripura', 'Dhalai', 'North Tripura'] },
  { code: 'UP', name: 'Uttar Pradesh', capital: 'Lucknow', coords: [80.9462, 26.8467], districts: ['Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Allahabad'] },
  { code: 'UT', name: 'Uttarakhand', capital: 'Dehradun', coords: [78.0322, 30.3165], districts: ['Dehradun', 'Haridwar', 'Roorkee', 'Haldwani', 'Rudrapur'] },
  { code: 'WB', name: 'West Bengal', capital: 'Kolkata', coords: [88.3639, 22.5726], districts: ['Kolkata', 'Howrah', 'Darjeeling', 'Asansol', 'Siliguri'] },
  { code: 'AN', name: 'Andaman and Nicobar Islands', capital: 'Port Blair', coords: [92.7265, 11.6670], districts: ['South Andaman', 'North and Middle Andaman', 'Nicobar'] },
  { code: 'CH', name: 'Chandigarh', capital: 'Chandigarh', coords: [76.7794, 30.7333], districts: ['Chandigarh'] },
  { code: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu', capital: 'Daman', coords: [72.8397, 20.3974], districts: ['Daman', 'Diu', 'Dadra and Nagar Haveli'] },
  { code: 'DL', name: 'Delhi', capital: 'New Delhi', coords: [77.2090, 28.6139], districts: ['Central Delhi', 'New Delhi', 'South Delhi', 'East Delhi', 'North Delhi'] },
  { code: 'JK', name: 'Jammu and Kashmir', capital: 'Srinagar', coords: [74.7973, 34.0837], districts: ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Kathua'] },
  { code: 'LA', name: 'Ladakh', capital: 'Leh', coords: [77.5828, 34.1526], districts: ['Leh', 'Kargil'] },
  { code: 'LD', name: 'Lakshadweep', capital: 'Kavaratti', coords: [72.6369, 10.5667], districts: ['Lakshadweep'] },
  { code: 'PY', name: 'Puducherry', capital: 'Puducherry', coords: [79.8083, 11.9416], districts: ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'] }
];

module.exports = statesData;
